### ISSUE TITLE
Aider les équipes Neo à faire fonctionner la VOiP

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-android#1055]
Les appels ne fonctionnent pas sur Tchap android sur les Néo

Les appels fonctionnent sur le web pc et mobile sur le réseau des Néo selon José.

Nous supposons que la configuration du proxy n'est pas prise en compte par la [librairie webrtc](https://github.com/jitsi/webrtc/) : https://groups.google.com/g/discuss-webrtc/c/BfpkeFe0Qy4?pli=1

```[tasklist]
### Tasks
- [x] Fork de la lib webrtc https://github.com/tchapgouv/webrtc/
- [x] Application du [patch](https://groups.google.com/g/discuss-webrtc/c/BfpkeFe0Qy4?pli=1) https://github.com/tchapgouv/webrtc/compare/13f5eaef79cacf4b9426166d452c139da1c1594c..9b8dbcb6302de77f5727db060374fc007d7b1f4f
- [x] Compiler la librairie https://github.com/tchapgouv/webrtc/pull/2
- [x] Générer le package AAR pour android https://www.jitpack.io/#tchapgouv/webrtc
- [x] Importer le nouveau package dans Tchap android https://github.com/tchapgouv/tchap-android/pull/1063
- [x] Injecter la configuration proxy du système dans webrtc https://github.com/tchapgouv/tchap-android/pull/1063/files#diff-fbf51128dc068ba2e0a8b4a2d76fe8ac0fdd5e68ca65ce41a6b2c0535c50cb8f
- [ ] Tester avec un proxy
```

**Comment by yostyle** [comment]
En attente : 
- des retours des tests de l'équipe Néo
- des tests effectués par @MatMaul
