### ISSUE TITLE
Secure backup is required

### ISSUE THREAD

**Issue by yostyle** [tchapgouv/tchap-android#988]
Mettre en place un mécanisme qui permette d'inciter l'utilisateur à activer la sauvegarde automatique des clés de chiffrement des message (le key Backup).

Pour pouvoir activer cette sauvegarde automatique, il faut que l'appareil soit vérifié avec le cross-signing. Sur Android le cross signing est initialisée automatiquement.

Une clé de paramétrage existe dans le fichier back-end well-known de configuration qui permet d'amorcer le processus. Cette clé est `secure_backup_required`.

Le well-known étant vide ou non disponible actuellement sur Tchap, on va forcer cette valeur à TRUE dans les clients.

Il y'a déjà un existant chez BWI https://gitlab.opencode.de/bwi/bundesmessenger/clients/bundesmessenger-android/-/blame/master/vector/src/bwi/java/de/bwi/messenger/features/location_sharing/BwiWellknownService.kt#L64
```[tasklist]
### Tasks
- [x] Add feature flag
- [x] Activer l'obligation du secure backup
- [ ] ~~Rappel tous les X jours~~
- [x] Revoir le wording
```

**Comment by yostyle** [comment]
![image](https://github.com/tchapgouv/tchap-android/assets/1191674/b87699cb-4c8c-4191-b3be-5473b7340113)

Après le login et à l'ouverture de l'app la vérification est obligatoire. Le comportement le wording sont à revoir.

**Comment by yostyle** [comment]
<img width="505" alt="image" src="https://github.com/tchapgouv/tchap-android/assets/1191674/6ff8c75a-8178-486e-ba6e-a56b018a9db0">

Après le login, la clé de récupération est générée automatiquement et la sauvegarde automatique est activée.

**Comment by areox-net** [comment]
Il faudrait le plus possible que les boutons correspondent à des actions.
Voici le wording que je propose:

### Vérifier cet appareil
Vérifiez cet appareil pour accéder à vos messages.

- **Vérifier avec un autre appareil >**
- **Vérifier avec le Code de Récupération >**
~~Si vous n'avez pas accès à un appareil existant~~
- **Générer un nouveau Code de Récupération >**
Uniquement si vous avez perdu votre Code et n'avez aucun autre appareil connecté à Tchap.
